sonar.projectKey=JesusJC15_salud-de-una-mobile
sonar.organization=jesusjc15

sonar.sources=app,src
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.ts,src/tests/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=android/**,assets/**,coverage/**,node_modules/**,.expo/**,**/*.d.ts,**/README.md
sonar.coverage.exclusions=app/**,src/tests/**,src/types/**,src/mocks/**,src/ui/**,src/components/**,src/hooks/**,src.providers/**,src/constants/**,src/forms/**,src/config/**,src/store/**,src/features/**/*-screen.tsx,src/features/**/use-*.ts,src/services/api/**,src/services/auth/token-storage.ts
